### ISSUE TITLE
Make a website

### ISSUE THREAD

**Issue by kiknaio** [jashmenn/cryptocurrencies-in-four-words#3]
Hello Nate,

It would be great to make a website where all these coins will be listed with the links to the websites and whitepapers.
Also, users will be allowed to make pull requests to add more coins and descriptions.
Small but useful features:
* Fuzzy search
* Pin favorite coins
* Website also will be the PWA (this will allow mobile users to save the website as a native mobile app and use it as a reference)
* Coin voting

If you are interested, it would be a pleasure for me to work with you.

**Comment by jashmenn** [comment]
Yeah I'd love to -- where do we start?

**Comment by kiknaio** [comment]
Great! First of all, maybe I will prototype a website design to get the general overview of how should it look and work.

**Comment by jashmenn** [comment]
feel free to submit a pull request
