### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bfischer1121** [jashmenn/cryptocurrencies-in-four-words#8]
Can you add a license to the repo? Preferably MIT ;-)

**Comment by jashmenn** [comment]
@bfischer1121 - we'll use "Attribution-ShareAlike 4.0 International" https://creativecommons.org/licenses/by-sa/4.0/ 

I'd love to hear about what you're working on! (And don't forget to checkout the Google doc, as it has the most up-to-date descriptions)

**Comment by bfischer1121** [comment]
Hey so I'm working on cryptoscreener.io. It's not released yet but I could see this data being used on the exchange pages next to currency names, as part of preview cards that show on hover, and in a future "Explore" section that let's users browse and compare tokens by industry in a fun way.

It would be in the same database as a bunch of other data from various sources, some of which is proprietary. So I'm not sure how a sharealike license would work for that. If a record contains this data does the whole record then fall under the license?

**Comment by jashmenn** [comment]
No, the whole record wouldn't -- just a list of (coin,description) pairs, if you decide to change and republish

**Comment by bfischer1121** [comment]
Great -- thanks for the clarification
